export PHOENIX_ENABLE_AUTH=True
export PHOENIX_SECRET=3413f9a7735bb780c6b8e4db7d946a492b64d26112a955cdea6a797f4c833593

https://arize.com/generative-ai/

https://arize.com/docs/ax

https://arize.com/model-monitoring/

https://arize.com/?post_type=course&p=14924

https://colab.research.google.com/drive/1FIJLgqQrd255-cLIKgTeU2ToTQhRQuv9?usp=sharing

https://colab.research.google.com/github/Arize-ai/tutorials/blob/main/python/llm/experiments/summarization-experiment.ipynb

https://colab.research.google.com/github/Arize-ai/tutorials/blob/main/python/llm/experiments/summarization-experiment.ipynb#scrollTo=T7QYiS3gl40N
SPACE_ID
API_KEY

- [Arize Documentation](https://docs.arize.com/phoenix/notebooks)
- [LLM Evaluation: The Definitive Guide](https://arize.com/blog-course/llm-evaluation-the-definitive-guide/)
- [LLM Evaluation: Assessing Large Language Models Using Their Peers](https://arize.com/blog-course/assessing-large-language-models/)
- [Navigating LLM Leaderboards for Model Selection: An Overview of Benchmark Evaluations](https://arize.com/blog-course/llm-leaderboards-benchmarks/)
- [Evals from OpenAI: Simplifying and Streamlining LLM Evaluation](https://arize.com/blog-course/evals-openai-simplifying-llm-evaluation/)

Github Repos:

- [Phoenix evals](https://github.com/Arize-ai/phoenix/tree/main/tutorials/evals)
- [Resources for Evaluation of LLMs / Generative AI](https://github.com/rajshah4/LLM-Evaluation#resources-for-evaluation-of-llms--generative-ai)

openssl s_client -connect otlp.arize.com:443 -showcerts </dev/null \

 | awk '/BEGIN CERTIFICATE/{f="y"} f{print} /END CERTIFICATE/{f=""}' \

 \> /Users/XXXXXX



import certifi

os.environ['GRPC_DEFAULT_SSL_ROOTS_FILE_PATH'] = certifi.where()



import certifi

os.environ['GRPC_DEFAULT_SSL_ROOTS_FILE_PATH'] = “/Users/your-path-here”



E0918 15:54:49.318727000 8335483072 ssl_transport_security.cc:1501]    Handshake failed with fatal error SSL_ERROR_SSL: error:0A000086:SSL routines::certificate verify failed.
Traceback (most recent call last):
  File "/Users/huanglin/miniconda3/envs/poc-llm/lib/python3.11/site-packages/arize/experimental/datasets/core/client.py", line 478, in create_dataset
    writer, metadata_reader = flight_client.do_put(
                              ^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_flight.pyx", line 1732, in pyarrow._flight.FlightClient.do_put
  File "pyarrow/_flight.pyx", line 68, in pyarrow._flight.check_flight_status
pyarrow._flight.FlightUnavailableError: Flight returned unavailable error, with message: failed to connect to all addresses; last error: UNKNOWN: ipv4:34.117.96.240:443: Ssl handshake failed: SSL_ERROR_SSL: error:0A000086:SSL routines::certificate verify failed. gRPC client debug context: UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:34.117.96.240:443: Ssl handshake failed: SSL_ERROR_SSL: error:0A000086:SSL routines::certificate verify failed {grpc_status:14, created_time:"2025-09-18T15:54:49.321443-04:00"}. Additionally, could not finish writing record batches before closing. Client context: IOError: Could not write record batch to stream (server disconnect?). Detail: flight::ServerErrorTagStatusDetail

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/huanglin/Bitbucket/llmops-poc/template-test/arize-ax/experiment.py", line 30, in <module>
    dataset_id = arize_client.create_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huanglin/miniconda3/envs/poc-llm/lib/python3.11/site-packages/arize/experimental/datasets/core/client.py", line 491, in create_dataset
    raise RuntimeError(
RuntimeError: Failed to create dataset: name=docs-qa-new-55594, type=1 for space_id=U3BhY2U6MjY4Mjk6RXl5dQ==

